admin_index:
    path:     /
    defaults: { _controller: "PLATFORMBundle:Admin:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "PLATFORMBundle:Admin:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "PLATFORMBundle:Admin:new" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "PLATFORMBundle:Admin:delete" }
    methods:  DELETE
