user_index:
    path:     /
    defaults: { _controller: "PLATFORMBundle:Admin:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "PLATFORMBundle:Admin:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "PLATFORMBundle:Admin:new" }
    methods:  [GET, POST]



user_delete:
    path:     /{id}/delete
    defaults: { _controller: "PLATFORMBundle:Admin:delete" }
    methods:  DELETE
