location_index:
    path:     /
    defaults: { _controller: "PLATFORMBundle:Location:index" }
    methods:  GET

location_show:
    path:     /{id}/show
    defaults: { _controller: "PLATFORMBundle:Location:show" }
    methods:  GET

location_new:
    path:     /new
    defaults: { _controller: "PLATFORMBundle:Location:new" }
    methods:  [GET, POST]

location_edit:
    path:     /{id}/edit
    defaults: { _controller: "PLATFORMBundle:Location:edit" }
    methods:  [GET, POST]

location_delete:
    path:     /{id}/delete
    defaults: { _controller: "PLATFORMBundle:Location:delete" }
    methods:  DELETE
