platform_user:
    resource: "@PLATFORMBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

platform_monactivite:
    resource: "@PLATFORMBundle/Resources/config/routing/monactivite.yml"
    prefix:   /monactivite

monactivite_show:
    path:     /{id}/show
    defaults: { _controller: "PLATFORMBundle:Profil:show" }
    methods:  GET


platform_homepage:
    path:     /
    defaults: { _controller: PLATFORMBundle:Profil:search }

platform_search:
    path:     /search
    defaults: { _controller: PLATFORMBundle:Profil:index }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: PLATFORMBundle:Profil:edit }
    methods:  [GET, POST]

profil:
    path:     /profil
    defaults: { _controller: PLATFORMBundle:Profil:profil }

creation_profil:
    path:     /create
    defaults: { _controller: PLATFORMBundle:Profil:create }

chat_profil:
    path:     /profil_chat
    defaults: { _controller: PLATFORMBundle:Profil:chat }

my_profil:
    path:     /MyProfil
    defaults: { _controller: PLATFORMBundle:Profil:MyProfil }

chat_profil_bis:
    path:     /profil_chat_bis
    defaults: { _controller: PLATFORMBundle:Profil:chatProfilBis }

connection_profil:
    path:     /connection
    defaults: { _controller: PLATFORMBundle:Profil:connection }
