platform_homepage:
    path:     /
    defaults: { _controller: PLATFORMBundle:Profil:index }

profil:
    path:     /profil
    defaults: { _controller: PLATFORMBundle:Profil:profil }

creation_profil:
    path:     /create
    defaults: { _controller: PLATFORMBundle:Profil:create }

search_profil:
    path:     /search
    defaults: { _controller: PLATFORMBundle:Profil:search }
