platform_homepage:
    path:     /
    defaults: { _controller: PLATFORMBundle:Profil:index }

profil:
    path:     /profil
    defaults: { _controller: PLATFORMBundle:Profil:profil }

creation_profil:
    path:     /create
    defaults: { _controller: PLATFORMBundle:Profil:create }

search_profil:
    path:     /search
    defaults: { _controller: PLATFORMBundle:Profil:search }

chat_profil:
    path:     /profil_chat
    defaults: { _controller: PLATFORMBundle:Profil:chat }

my_profil:
    path:     /MyProfil
    defaults: { _controller: PLATFORMBundle:Profil:MyProfil }

chat_profil_bis:
    path:     /profil_chat_bis
    defaults: { _controller: PLATFORMBundle:Profil:chatProfilBis }

connection_profil:
    path:     /profil_connection
    defaults: { _controller: PLATFORMBundle:Profil:connection }