platform_user:
    resource: "@PLATFORMBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

platform_homepage:
    path:     /
    defaults: { _controller: PLATFORMBundle:Profil:index }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "PLATFORMBundle:Profil:edit" }
    methods:  [GET, POST]

profil:
    path:     /profil
    defaults: { _controller: PLATFORMBundle:Profil:profil }

creation_profil:
    path:     /create
    defaults: { _controller: PLATFORMBundle:Profil:create }

search_profil:
    path:     /search
    defaults: { _controller: PLATFORMBundle:Profil:search }

chat_profil:
    path:     /profil_chat
    defaults: { _controller: PLATFORMBundle:Profil:chat }

my_profil:
    path:     /MyProfil
    defaults: { _controller: PLATFORMBundle:Profil:MyProfil }

chat_profil_bis:
    path:     /profil_chat_bis
    defaults: { _controller: PLATFORMBundle:Profil:chatProfilBis }
