<?php

namespace PLATFORMBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindOne(){
        $qb = $this->createQueryBuilder('F');
        $qb->select('F')
            ->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
