<?php

namespace PLATFORMBundle\Repository;

/**
 * MonActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
