PLATFORMBundle\Entity\File:
    type: entity
    table: null
    repositoryClass: PLATFORMBundle\Repository\FileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        filename:
            type: string
            length: 255
        url:
            type: string
            length: 255
        alt:
            type: string
            length: 255

    oneToOne:
        fichier:
            targetEntity: PLATFORMBundle\Entity\User
            inversedBy: file
            cascade: ["all"]
    lifecycleCallbacks: {  }
