PLATFORMBundle\Entity\FileImage:
    type: entity
    table: null
    repositoryClass: PLATFORMBundle\Repository\FileImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        filename:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        alt:
            type: string
            length: 255
            nullable: true

    oneToOne:
        fichier:
            targetEntity: PLATFORMBundle\Entity\User
            inversedBy: file
            cascade: ["all"]
    lifecycleCallbacks: {  }
