PLATFORMBundle\Entity\MonActivite:
    type: entity
    table: null
    repositoryClass: PLATFORMBundle\Repository\MonActiviteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
            nullable: true
        time1:
            type: time
            nullable: true
        time2:
            type: time
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        profil:
            targetEntity: PLATFORMBundle\Entity\User
            inversedBy: monActivites
            cascade: ["all"]

    manyToMany:
        locations:
            targetEntity: PLATFORMBundle\Entity\Location
            mappedBy: monActivites
            cascade: ["all"]


        activites:
            targetEntity: PLATFORMBundle\Entity\Activity
            mappedBy: monActivites
            cascade: ["all"]