PLATFORMBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255

        company:
            type: string
            length: 255
            nullable: true
        position:
            type: string
            length: 255
            nullable: true
        insead:
            type: string
            length: 255
            nullable: true



    lifecycleCallbacks: {  }
    oneToOne:
        file:
            targetEntity: PLATFORMBundle\Entity\FileImage
            mappedBy: fichier
            cascade: ["all"]
    oneToMany:
        monActivites:
            targetEntity: PLATFORMBundle\Entity\MonActivite
            mappedBy: profil
            cascade: ["all"]

